_BASE_: "base.yml"

MODEL:
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_WEIGHT: 0.1

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (6000,)
  MAX_ITER: 8000

DATASETS:
  TRAIN: ('rsod_trainval_novel2_1shot_seed1',)

OUTPUT_DIR: "checkpoints/rsod/split2/1shot_inc_clp"