_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.00015
  GAMMA: 0.1
  STEPS:  (10000,)
  MAX_ITER: 12000
  WARMUP_ITERS: 100

DATASETS:
  TRAIN: ('nwpu_trainval_novel2_1shot_seed1',)

OUTPUT_DIR: "checkpoints/nwpu/split2_fpn/1shot_fsce"
