_BASE_: "base.yml"
MODEL:
  ROI_HEADS:
    COEFF: 0.01
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_WEIGHT: 0.1

SOLVER:
  BASE_LR: 0.0015
  STEPS:  (10000,)
  MAX_ITER: 13000


DATASETS:
  TRAIN: ('rsod_trainval_novel3_10shot_seed10',)

OUTPUT_DIR: "checkpoints/rsod/split3/10shot_inc_clp"