_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0001
  STEPS:  (6000,)
  MAX_ITER: 8000

DATASETS:
  TRAIN: ('rsod_trainval_novel3_1shot_seed1',)

OUTPUT_DIR: "checkpoints/rsod/split3/1shot_inc_clp"



TEST:
  EVAL_PERIOD: 1000
