_BASE_: "base.yml"

DATASETS:
  TRAIN: ('rsod_trainval_novel1_10shot_seed10',)

SOLVER:
  BASE_LR: 0.0004
  STEPS:  (8000,)
  MAX_ITER: 10000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/rsod/split1/10shot_baseline"