_BASE_: "base.yml"

DATASETS:
  TRAIN: ('rsod_trainval_novel1_1shot_seed1',)

SOLVER:
  BASE_LR: 0.0001
  STEPS:  (5000,7000)
  MAX_ITER: 6000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/rsod/split1/1shot_baseline"