_BASE_: "../split.yml"
MODEL:

  PROPOSAL_GENERATOR:
    FREEZE: False

  ROI_HEADS:
    COEFF: 0.0
    NAME: "RedetectROIHeadsV1"

    COSINE_ON: True
  ROI_BOX_HEAD:
    REDETECT: 
      LOSS: "MS"
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.5
      MLP_FEATURE_DIM: 128
      DECAY:
        ENABLED: True
        STEPS: [4000, 10000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
    PROTOTYPE:
      ENABLED: false

DATASETS:
  TRAIN: ('nwpu_trainval_novel1_10shot_seed10',)
SOLVER:
  IMS_PER_BATCH: 4
  TEST_IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  GAMMA: 0.1
  STEPS:  (10000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 150
