_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (10000,)
  GAMMA: 0.5
  MAX_ITER: 16000
  WARMUP_ITERS: 1000


DATASETS:
  TRAIN: ('dior_trainval_novel1_20shot_seed23',)

OUTPUT_DIR: "checkpoints/dior/split1/20shot_rsdmk"
TEST:
  EVAL_PERIOD: 800