_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0004
  STEPS:  (10000,)
  MAX_ITER: 12000
  WARMUP_ITERS: 100


DATASETS:
  TRAIN: ('rsod_trainval_novel1_10shot_seed10',)

OUTPUT_DIR: "checkpoints/rsod/split1/10shot_rsdmk"