_BASE_: "../split.yml"
MODEL:
  PROPOSAL_GENERATOR:
    FREEZE: False

  ROI_HEADS:
    NAME: "StandardROIHeads"
    OUTPUT_LAYER: "FastRCNNOutputLayers"

  ROI_BOX_HEAD:
    
    PROTOTYPE:
      ENABLED: False
      DISABLE_PROTOTYPE_GRAD: true    

SOLVER:
  BASE_LR: 0.0001
  GAMMA: 0.5
  STEPS:  (3500,4200)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 200
