_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (6000,)
  MAX_ITER: 8000
  WARMUP_ITERS: 300

DATASETS:
  TRAIN: ('dior_trainval_novel3_3shot_seed3',)

OUTPUT_DIR: "checkpoints/dior/split3/3shot_fsce"