_BASE_: "base.yml"

SOLVER:
  IMS_PER_BATCH: 4
  TEST_IMS_PER_BATCH: 4
  #BASE_LR: 0.001
  BASE_LR: 0.0003
  GAMMA: 0.1
  STEPS:  (10000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 4000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/nwpu/split2_fpn/10shot_inc_clp"