_BASE_: "../split.yml"
TRAINER: "IncTrainer"

MODEL:
  ROI_HEADS:
    NAME: "IncContrastROIHeads"

    COSINE_ON: True
    COEFF: 0.1

  ROI_BOX_HEAD:
    BOX_REG_WEIGHT: 1.0
    BOX_CLS_WEIGHT: 1.0
    REDETECT:
      LOSS: "WS"
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.3
      MLP_FEATURE_DIM: 128
      DECAY:
        ENABLED: True
        STEPS: [6000, 10000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
    PROTOTYPE:
      ENABLED: True
      DATASET: "NWPU"
      DISABLE_PROTOTYPE_GRAD: true
      PATH: "checkpoints/nwpu/prototype/split2/prototype.feature"


  PROPOSAL_GENERATOR:
    FREEZE: False

DATASETS:
  TRAIN: ('nwpu_trainval_novel2_10shot_seed10',)
