_BASE_: "../rsod_base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 3

SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (1500,)
  BASE_LR: 0.004
  MAX_ITER: 10000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 10000
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 400

OUTPUT_DIR: "checkpoints/rsod/base_train/split"
