_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  WEIGHTS: "checkpoints/rsod/base_train/split2/model_best.pth"
  ROI_HEADS:
    OUTPUT_CLS: "FocalLoss_Outputs"
DATASETS:
  TRAIN: ('rsod_trainval_base2',)
  TEST: ('rsod_test_base2',)
SOLVER:
  STEPS: (9000, 12000)
  BASE_LR: 0.004
  MAX_ITER: 15000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 10000
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 1000

OUTPUT_DIR: "checkpoints/rsod/base_train/split2"

