_BASE_: "base.yml"

LOGGING_INTERVAL: 20
MODEL:

  WEIGHTS: "weights/RSOD_R101_split3.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001  ## cover all bounding box
  ROI_BOX_HEAD:
    PROTOTYPE:
      SAMPLE: True
DATASETS:
  TRAIN: ('rsod_trainval_base3_prototype',)
  TEST: ('rsod_trainval_base3_prototype',)
DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: "checkpoints/rsod/prototype/split3"