_BASE_: "../split.yml"
MODEL:

  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
    NAME: "StandardROIHeads"

    OUTPUT_LAYER: "FastRCNNOutputLayers"
  ROI_BOX_HEAD:
    PROTOTYPE:
      ENABLED: False
      DATASET: "DIOR"
      DISABLE_PROTOTYPE_GRAD: true    


SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  GAMMA: 0.5
  STEPS:  (3500,4200)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 100
