_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0001
  STEPS:  (3000,)
  MAX_ITER: 4000
  WARMUP_ITERS: 100

DATASETS:
  TRAIN: ('nwpu_trainval_novel1_1shot_seed1',)

OUTPUT_DIR: "checkpoints/nwpu/split1_fpn/1shot_fsce"