_BASE_: "../nwpu_base.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "work_dirs/fsce_resnet101_base1_all_redetect/model_reset_surgery.pth"

  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False

  ROI_HEADS:
    NUM_CLASSES: 10
    BATCH_SIZE_PER_IMAGE: 256
    FREEZE_FEAT: False
    UNFREEZE_FC1: False
    UNFREEZE_FC2: False

  ROI_BOX_HEAD:
    PROTOTYPE:
      ENABLED: False

INPUT:
  MIN_SIZE_TEST: 800
  CROP:
    ENABLED: True
DATASETS:
  TEST: ('nwpu_test_all1',)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  GAMMA: 0.5
  STEPS:  (3500,4200)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 100

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 400
