_BASE_: "base.yml"
MODEL:
  PROPOSAL_GENERATOR:
    FREEZE: False
DATASETS:
  TRAIN: ('nwpu_trainval_novel2_1shot_seed1',)
  # TRAIN: ('nwpu_trainval_novel2_1shot_seed2',)

SOLVER:
  BASE_LR: 0.004
  STEPS:  (7000, )
  MAX_ITER: 8000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/nwpu/split2_fpn/1shot_baseline"