_BASE_: "base.yml"

DATASETS:
  TRAIN: ('nwpu_trainval_novel2_5shot_seed5',)

SOLVER:
  BASE_LR: 0.0005
  STEPS:  (7000, )
  MAX_ITER: 8000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/nwpu/split2_fpn/5shot_baseline"