_BASE_: "../split.yml"

MODEL:
  ROI_HEADS:
    OUTPUT_LAYER: "FastRCNNOutputLayers"
  PROPOSAL_GENERATOR:
    FREEZE: False
  ROI_BOX_HEAD:
    PROTOTYPE:
      ENABLED: False
      DATASET: "NWPU"
      DISABLE_PROTOTYPE_GRAD: true
SOLVER:
  IMS_PER_BATCH: 4
  GAMMA: 0.5
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 100
