_BASE_: "base.yml"

DATASETS:
  TRAIN: ('dior_trainval_novel1_10shot_seed10',)

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (8000,)
  MAX_ITER: 10000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/dior/split1/10shot_baseline"