_BASE_: "base.yml"

DATASETS:
  TRAIN: ('dior_trainval_novel1_20shot_seed20',)

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (8000,)
  MAX_ITER: 14000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/dior/split1/20shot_baseline"