_BASE_: "base.yml"

DATASETS:
  TRAIN: ('dior_trainval_novel1_3shot_seed2',)

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (6000, )
  MAX_ITER: 8000
  WARMUP_ITERS: 300

OUTPUT_DIR: "checkpoints/dior/split1/3shot_baseline"