_BASE_: "base.yml"
MODEL:
  ROI_HEADS:
    COEFF: 0.01
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_WEIGHT: 0.02

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (10000,)
  MAX_ITER: 13000


DATASETS:
  TRAIN: ('dior_trainval_novel3_10shot_seed32',)

OUTPUT_DIR: "checkpoints/dior/split3/10shot_inc_clp"