_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.001
  STEPS:  (6000,)
  MAX_ITER: 8000

DATASETS:
  TRAIN: ('dior_train_novel3_50shot_seed1',)

OUTPUT_DIR: "checkpoints/dior/split3/1shot_inc_clp"



TEST:
  EVAL_PERIOD: 1000
