_BASE_: "base.yml"
MODEL:
  ROI_HEADS:
    COEFF: 0.1
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_WEIGHT: 0.1
SOLVER:
  BASE_LR: 0.0002
  STEPS:  (10000,)
  MAX_ITER: 14000


DATASETS:
  TRAIN: ('dior_trainval_novel3_20shot_seed25',)

OUTPUT_DIR: "checkpoints/dior/split3/20shot_inc_clp"