_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0006
  STEPS:  (6000,)
  MAX_ITER: 8000
  WARMUP_ITERS: 300

DATASETS:
  TRAIN: ('rsod_trainval_novel1_3shot_seed3',)

OUTPUT_DIR: "checkpoints/rsod/split1/3shot_fsce"