_BASE_: "base.yml"


DATASETS:
  TRAIN: ('nwpu_trainval_novel3_1shot_seed1',)

SOLVER:
  BASE_LR: 0.0004
  STEPS:  (4000, 4500)
  MAX_ITER: 5000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/nwpu/split3_fpn/1shot_baseline"