_BASE_: "base.yml"

DATASETS:
  TRAIN: ('nwpu_trainval_novel3_3shot_seed2',)

SOLVER:
  BASE_LR: 0.0004
  STEPS:  (5000, 6000)
  MAX_ITER: 7000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/nwpu/split3_fpn/3shot_baseline"