_BASE_: "base.yml"

DATASETS:
  TRAIN: ('nwpu_trainval_novel3_5shot_seed8',)

SOLVER:
  BASE_LR: 0.0004
  STEPS:  (6000,7000)
  MAX_ITER: 8000
  WARMUP_ITERS: 100


OUTPUT_DIR: "checkpoints/nwpu/split3_fpn/5shot_baseline"