_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  WEIGHTS: "checkpoints/dior/all/model_best.pth"

  MASK_ON: False

  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ('dior_train_all1',)
  TEST: ('dior_val_all1',)
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (5000, 7000)
  BASE_LR: 0.004
  MAX_ITER: 10000
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 12000
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 500

OUTPUT_DIR: "checkpoints/dior/all"

