_BASE_: "../split.yml"

MODEL:
  ROI_HEADS:
    COEFF: 0.0
    NAME: "RedetectROIHeadsV1"
    COSINE_ON: True

  ROI_BOX_HEAD:
    REDETECT:
      LOSS: "MS"
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.9
      MLP_FEATURE_DIM: 128
      DECAY:
        ENABLED: True
        STEPS: [6000, 10000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
    PROTOTYPE:
      ENABLED: false

  PROPOSAL_GENERATOR:
    FREEZE: False

SOLVER:
  IMS_PER_BATCH: 4
  TEST_IMS_PER_BATCH: 4
