_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (6000,)
  MAX_ITER: 8000
  WARMUP_ITERS: 100

DATASETS:
  TRAIN: ('dior_trainval_novel1_1shot_seed1',)

OUTPUT_DIR: "checkpoints/dior/split1/1shot_inc_clp"