_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (6000, 9000)
  MAX_ITER: 10000
  WARMUP_ITERS: 100

DATASETS:
  TRAIN: ('dior_trainval_novel1_5shot_seed5',)

OUTPUT_DIR: "checkpoints/dior/split1/5shot_inc_clp"