_BASE_: "base.yml"
# MODEL:
  # WEIGHTS: "checkpoints/rsod/split3/10shot_fsce/model_best_novel.pth"
SOLVER:
  BASE_LR: 0.0006
  STEPS:  (10000,)
  MAX_ITER: 12000


DATASETS:
  TRAIN: ('rsod_trainval_novel3_10shot_seed10',)

OUTPUT_DIR: "checkpoints/rsod/split3/10shot_fsce"

TEST:
  EVAL_START: 3000
