_BASE_: "../split.yml"
TRAINER: "IncTrainer"

MODEL:
  ROI_HEADS:
    NAME: "ContrastiveROIHeads"

    COSINE_ON: True
    
    COEFF: 0.0

  PROPOSAL_GENERATOR:
    FREEZE: False
  ROI_BOX_HEAD:
    BOX_REG_WEIGHT: 1.0
    BOX_CLS_WEIGHT: 1.0
    CONTRASTIVE_BRANCH:
      LOSS_VERSION: "V1"
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.2
      MLP_FEATURE_DIM: 128
      DECAY:
        ENABLED: True
        STEPS: [6000, 10000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
    PROTOTYPE:
      ENABLED: False


SOLVER:
  BASE_LR: 0.0001
  GAMMA: 0.1
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 100

