_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"

  MASK_ON: False
  RESNETS:
    DEPTH: 101
INPUT:
  MIN_SIZE_TRAIN: (480, 608, 736, 800)
  MIN_SIZE_TEST: 800
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 200