_BASE_: "base.yml"


SOLVER:
  BASE_LR: 0.0003
  GAMMA: 0.1
  STEPS:  (10000,)
  MAX_ITER: 12000

DATASETS:
  TRAIN: ('nwpu_trainval_novel2_5shot_seed5',)

OUTPUT_DIR: "checkpoints/nwpu/split2_fpn/5shot_dmk"