_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 15


SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (12000, 14000)
  BASE_LR: 0.004
  MAX_ITER: 16000
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 10000

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 1000
