_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  WEIGHTS: "checkpoints/dior/base_train/split1/model_best.pth"
DATASETS:
  TRAIN: ('dior_train_base1',)
  TEST: ('dior_val_base1',)
SOLVER:
  STEPS: (12000, 18000)
  BASE_LR: 0.004
  MAX_ITER: 16000


OUTPUT_DIR: "checkpoints/dior/base_train/split1"

