_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  # WEIGHTS: "checkpoints/dior/base_train/split2/model_best.pth"
  # WEIGHTS: "work_dirs/fsce_resnet101_base1_all_redetect/model_reset_surgery.pth"

DATASETS:
  TRAIN: ('dior_train_base2',)
  TEST: ('dior_val_base2',)
SOLVER:
  STEPS: (12000, 14000)
  BASE_LR: 0.004
  MAX_ITER: 16000

OUTPUT_DIR: "checkpoints/dior/base_train/split2"

