_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  WEIGHTS: "checkpoints/dior/base_train/split3/model_best.pth"
  # WEIGHTS: "weights/dior_R101_fsce.pth"
  # WEIGHTS: "work_dirs/fsce_resnet101_base1_all_redetect/model_reset_surgery.pth"

DATASETS:
  TRAIN: ('dior_train_base3',)
  TEST: ('dior_val_base3',)
SOLVER:
  STEPS: (14000, 18000)
  BASE_LR: 0.004
  MAX_ITER: 20000

OUTPUT_DIR: "checkpoints/dior/base_train/split3"

