_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0001
  STEPS:  (6000,)
  MAX_ITER: 8000
  WARMUP_ITERS: 100

DATASETS:
  TRAIN: ('nwpu_trainval_novel1_5shot_seed5',)

OUTPUT_DIR: "checkpoints/nwpu/split1_fpn/5shot_inc_clp"