_BASE_: "../split.yml"
TRAINER: "IncTrainer"

MODEL:
  PROPOSAL_GENERATOR:
    FREEZE: False

  ROI_HEADS:
    COEFF: 1.0
    NAME: "IncContrastROIHeads"

    COSINE_ON: True
  ROI_BOX_HEAD:
    REDETECT: 
      LOSS: "WS"
    BOX_REG_WEIGHT: 1.0
    BOX_CLS_WEIGHT: 1.0
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.5
      MLP_FEATURE_DIM: 128
      DECAY:
        ENABLED: True
        STEPS: [4000, 10000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
    PROTOTYPE:
      ENABLED: True
      DATASET: "NWPU"
      DISABLE_PROTOTYPE_GRAD: true
      PATH: "checkpoints/nwpu/prototype/split1/prototype.feature" 

DATASETS:
  # TRAIN: ('nwpu_trainval_all1_10shot_seed10',)
  TRAIN: ('nwpu_trainval_novel1_10shot_seed10',)
SOLVER:
  IMS_PER_BATCH: 4
  TEST_IMS_PER_BATCH: 4
  #BASE_LR: 0.001
  BASE_LR: 0.0001
  GAMMA: 0.1
  STEPS:  (10000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 150
