_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (10000,)
  GAMMA: 0.5
  MAX_ITER: 16000


DATASETS:
  TRAIN: ('dior_trainval_novel2_20shot_seed21',)

OUTPUT_DIR: "checkpoints/dior/split2/20shot_rsdmk"
TEST:
  EVAL_PERIOD: 800