_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "weights/DIOR_R101.pth"
  ROI_HEADS:
    NUM_CLASSES: 7
  ROI_BOX_HEAD:
    PROTOTYPE:
      ENABLED: True
      SAMPLE: True
      MAX_INS_COUNT_PER_CATEGORY: -1
  RPN:
    PRE_NMS_TOPK_TEST: 2000
    POST_NMS_TOPK_TEST: 30
      
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MIN_SIZE_TEST: 800
SOLVER:
  STEPS: (800,)
  MAX_ITER: 4000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 500

TEST:
  AUG:
    ENABLED: False
  EVAL_PERIOD: 500
  DETECTIONS_PER_IMAGE: -1 ## use iou to get anchor, not score
