_BASE_: "base.yml"

LOGGING_INTERVAL: 20
MODEL:
  WEIGHTS: "weights/DIOR_R101_split1.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001  ## cover all bounding box
  ROI_BOX_HEAD:
    PROTOTYPE:
      SAMPLE: True
DATASETS:
  TRAIN: ('dior_trainval_base1_prototype',)
  TEST: ('dior_trainval_base1_prototype',)
DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: "checkpoints/dior/prototype/split1"