_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0002
  STEPS:  (10000,)
  MAX_ITER: 12000
  WARMUP_ITERS: 100


DATASETS:
  TRAIN: ('dior_trainval_novel1_10shot_seed10',)

OUTPUT_DIR: "checkpoints/dior/split1/10shot_fsce"