_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0001
  STEPS:  (10000,)
  MAX_ITER: 12000
  WARMUP_ITERS: 100

DATASETS:
  TRAIN: ('nwpu_trainval_novel3_1shot_seed1',)

OUTPUT_DIR: "checkpoints/nwpu/split3_fpn/1shot_inc_clp"