_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  # WEIGHTS: "weights/NWPU_R101_fsce.pth"
  # WEIGHTS: "work_dirs/fsce_resnet101_base1_all_redetect/model_reset_surgery.pth"

  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 7
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('nwpu_trainval_base3',)
  TEST: ('nwpu_test_base3',)
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (2000,)
  BASE_LR: 0.003
  MAX_ITER: 5000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 4000
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 200

OUTPUT_DIR: "checkpoints/nwpu/base_train/split3"

