_BASE_: "../nwpu_base.yaml"
MODEL:
  WEIGHTS: "weights/R-101.pkl"
  # WEIGHTS: "checkpoints/nwpu/base_train/split1/model_best.pth"
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 7
DATASETS:
  TRAIN: ('nwpu_trainval_base2',)
  TEST: ('nwpu_test_base2',)
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (2000, 2500)
  BASE_LR: 0.004
  MAX_ITER: 3000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 10000
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 200

OUTPUT_DIR: "checkpoints/nwpu/base_train/split2"

