_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:

  # WEIGHTS: "/home/lwz/code/SConPro/weights/R-101.pkl"
  WEIGHTS: "checkpoints/nwpu/base_train/split1/model_best.pth"

  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 7
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  #TRAIN: ('nwpu_trainval_base1', 'nwpu_trainval_base1')
  TRAIN: ('nwpu_trainval_base1',)
  TEST: ('nwpu_trainval_base1',)
SOLVER:
  STEPS: (800,)
  MAX_ITER: 5000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 4000

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 100

OUTPUT_DIR: "checkpoints/nwpu/base_train/split1"


SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (5000, 8000)
  MAX_ITER: 12000