_BASE_: "../nwpu_base.yaml"
LOGGING_INTERVAL: 20
MODEL:
  WEIGHTS: "checkpoints/nwpu/all/split1/model_best.pth"
  ROI_HEADS:
    NUM_CLASSES: 10
    SCORE_THRESH_TEST: 0.001  ## cover all bounding box
  RPN:
    PRE_NMS_TOPK_TEST: 2000
    POST_NMS_TOPK_TEST: 100
  ROI_BOX_HEAD:
    PROTOTYPE:
      ENABLED: True
      SAMPLE: True
      MAX_INS_COUNT_PER_CATEGORY: -1
DATASETS:
#   TRAIN: ('nwpu_trainval_all1_prototype',)
#   TEST: ('nwpu_trainval_all1_prototype',)
  TRAIN: ('nwpu_trainval_all1_prototype_num50',)
  TEST: ('nwpu_trainval_all1_prototype_num50',)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  STEPS: (80000,)
  IMS_PER_BATCH: 1
  TEST_IMS_PER_BATCH: 4  ## must be 1, or tsne feature will be confused
  MAX_ITER: 4000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 50000

TEST:
  AUG:
    ENABLED: False
  EVAL_PERIOD: 500
  DETECTIONS_PER_IMAGE: -1 ## use iou to get anchor, not score

OUTPUT_DIR: "checkpoints/nwpu/tsne/split1"