_BASE_: "base.yml"
MODEL:
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.05  ## cover all bounding box

  RPN:
    PRE_NMS_TOPK_TEST: 2000
    POST_NMS_TOPK_TEST: 30

DATASETS:
  TRAIN: ('nwpu_trainval_all1_prototype',)
  TEST: ('nwpu_trainval_all1_prototype',)


OUTPUT_DIR: "checkpoints/nwpu/prototype/select_shot"