_BASE_: "base.yml"

LOGGING_INTERVAL: 20
MODEL:
  # WEIGHTS: "/home/lwz/code/SConPro/weights/R-101.pkl"
  # WEIGHTS: "checkpoints/nwpu/base_train/split1/model_best.pth"
  WEIGHTS: "weights/NWPU_R101_fsce.pth"
  WEIGHTS: "weights/NWPU_R101_split1.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001  ## cover all bounding box
  ROI_BOX_HEAD:
    PROTOTYPE:
      SAMPLE: True
DATASETS:
  TRAIN: ('nwpu_trainval_base1_prototype',)
  TEST: ('nwpu_trainval_base1_prototype',)
DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: "checkpoints/nwpu/prototype/split1"