_BASE_: "../nwpu_base.yaml"
MODEL:
  # WEIGHTS: "checkpoints/nwpu/all/split1/model_best.pth"
  ROI_HEADS:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ('nwpu_trainval_all1',)
  TEST: ('nwpu_test_all1',)
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (1000, 3000,)
  BASE_LR: 0.004
  MAX_ITER: 5000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 4000
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 200

OUTPUT_DIR: "checkpoints/nwpu/all/"

