_BASE_: "base.yml"

SOLVER:
  BASE_LR: 0.0003
  STEPS:  (10000,)
  GAMMA: 0.5
  MAX_ITER: 16000


DATASETS:
  TRAIN: ('rsod_trainval_novel3_20shot_seed20',)

OUTPUT_DIR: "checkpoints/rsod/split3/20shot_rsdmk"
TEST:
  EVAL_PERIOD: 800